// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKUP4lmanC6Z1OJBPqEvaxIFMQv2KfYDM',
    appId: '1:375962179404:web:3e4cb4705d022f4722e1e9',
    messagingSenderId: '375962179404',
    projectId: 'calculadora-nota-final',
    authDomain: 'calculadora-nota-final.firebaseapp.com',
    storageBucket: 'calculadora-nota-final.firebasestorage.app',
    measurementId: 'G-67EGBJNFDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHDdw2QJtwR-W9M7a45tPCZ7jZb-D5wqo',
    appId: '1:375962179404:android:cd9836ecfcf9d63c22e1e9',
    messagingSenderId: '375962179404',
    projectId: 'calculadora-nota-final',
    storageBucket: 'calculadora-nota-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQeAPxGJFUOpxodvIiei6W1ifWaJ2Rluk',
    appId: '1:375962179404:ios:5ad91097cfbe2a2722e1e9',
    messagingSenderId: '375962179404',
    projectId: 'calculadora-nota-final',
    storageBucket: 'calculadora-nota-final.firebasestorage.app',
    iosBundleId: 'com.example.calculadoranotafinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQeAPxGJFUOpxodvIiei6W1ifWaJ2Rluk',
    appId: '1:375962179404:ios:5ad91097cfbe2a2722e1e9',
    messagingSenderId: '375962179404',
    projectId: 'calculadora-nota-final',
    storageBucket: 'calculadora-nota-final.firebasestorage.app',
    iosBundleId: 'com.example.calculadoranotafinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKUP4lmanC6Z1OJBPqEvaxIFMQv2KfYDM',
    appId: '1:375962179404:web:7961cdca9b18f56d22e1e9',
    messagingSenderId: '375962179404',
    projectId: 'calculadora-nota-final',
    authDomain: 'calculadora-nota-final.firebaseapp.com',
    storageBucket: 'calculadora-nota-final.firebasestorage.app',
    measurementId: 'G-87BGF4B3H7',
  );
}
