// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA7RtoovzTvON-4avOLykDRDEPCa2TpIc',
    appId: '1:391628714780:web:256d36188535facfd540d9',
    messagingSenderId: '391628714780',
    projectId: 'calculadoranotafinal',
    authDomain: 'calculadoranotafinal.firebaseapp.com',
    storageBucket: 'calculadoranotafinal.firebasestorage.app',
    measurementId: 'G-7JKG497850',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnn6SfJeuyCtPOMnTuFtRjZW1G5bW0yQ8',
    appId: '1:391628714780:android:6dbfaa6ff58f459bd540d9',
    messagingSenderId: '391628714780',
    projectId: 'calculadoranotafinal',
    storageBucket: 'calculadoranotafinal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzV33vKGhyMUuYV81ENVPVwnjJQG1D3RM',
    appId: '1:391628714780:ios:a4f7588b4d9fc73ad540d9',
    messagingSenderId: '391628714780',
    projectId: 'calculadoranotafinal',
    storageBucket: 'calculadoranotafinal.firebasestorage.app',
    iosBundleId: 'com.example.calculadoranotafinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzV33vKGhyMUuYV81ENVPVwnjJQG1D3RM',
    appId: '1:391628714780:ios:a4f7588b4d9fc73ad540d9',
    messagingSenderId: '391628714780',
    projectId: 'calculadoranotafinal',
    storageBucket: 'calculadoranotafinal.firebasestorage.app',
    iosBundleId: 'com.example.calculadoranotafinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA7RtoovzTvON-4avOLykDRDEPCa2TpIc',
    appId: '1:391628714780:web:d20637db8c36f2e5d540d9',
    messagingSenderId: '391628714780',
    projectId: 'calculadoranotafinal',
    authDomain: 'calculadoranotafinal.firebaseapp.com',
    storageBucket: 'calculadoranotafinal.firebasestorage.app',
    measurementId: 'G-58PZGE6603',
  );
}
